### ISSUE TITLE
UX issues for Svelte+Complete run

### ISSUE THREAD

**Issue by codingthat** [phaserjs/create-game#5]
Hi!

Just wanted to report a few snags encountered with the Svelte+Complete option of `npm create @phaserjs/game@latest`.  Let me know if I should split these into individual issues.

# 1) Vulnerabilities

```
$ npm i
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

added 105 packages, and audited 106 packages in 5s

9 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (2 moderate, 1 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

OK, `npm audit fix` takes care of that.  But it can be a red flag to people trying it out to see "leaks memory" and "do not use it" written about something they've just installed.

# 2) Double-building?

The message

```
Building for production...
---------------------------------------------------------
❤️❤️❤️ Tell us about your game! - games@phaser.io ❤️❤️❤️
---------------------------------------------------------
```

is repeated when building just after installing:

```
$ npm run build

> template-svelte@1.1.1 build
> node log.js build & vite build --config vite/config.prod.mjs

Building for production...
---------------------------------------------------------
❤️❤️❤️ Tell us about your game! - games@phaser.io ❤️❤️❤️
---------------------------------------------------------
"GameObjects" is imported from external module "phaser" but never used in "src/game/EventBus.ts", "src/game/scenes/Boot.ts", "src/game/scenes/GameOver.ts", "src/game/scenes/MainMenu.ts", "src/game/scenes/Game.ts", "src/game/scenes/Preloader.ts" and "src/game/main.ts".
Building for production...
---------------------------------------------------------
❤️❤️❤️ Tell us about your game! - games@phaser.io ❤️❤️❤️
---------------------------------------------------------

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
  Wrote site to "build"
  ✔ done
```

This remains true even if the `build` script in `package.json` is altered to just do `vite build --config vite/config.prod.mjs` rather than the default `node log.js build & vite build --config vite/config.prod.mjs`.

# 3) Missing preview script

The build instructions above include the text `Run npm run preview to preview your production build locally.`, but:

```
$ npm run preview
npm error Missing script: "preview"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: [...]
```

**Comment by gammafp** [comment]
Hi, thanks for reporting the problem. create-game uses the templates that are uploaded to github in the Phaser Studio repository, in the case of svelte the link is this:

https://github.com/phaserjs/template-svelte

We will check the template to find out what the problem is, thank you very much.

**Comment by gammafp** [comment]
1) Fixed
2) Fixed, but: This seems normal with svelte-kit. Looks like svelte-kit builds the project creating some temp configuration.
3) You can run the preview now. Remember build the project before.

Thank you for report the issue.
